### ISSUE TITLE
 https://tutorgeeks.blogspot.com/2017/04/aws-s3-bucket-misconfiguration.html

### ISSUE THREAD

**Issue by Cybersecurity-Specialist** [tutorgeeks/AWS-Security-Assessment-Scripts#1]
Hi,

My name is Mark Lovinson from IZOOlogic working on behalf of our client, PayTM.
We are contacting you today to request the immediate removal of the following blogspot article that is a violation of the Paytm bug bounty rules found on **https://bugbounty.paytm.com/.**

URL : **_https://tutorgeeks.blogspot.com/2017/04/aws-s3-bucket-misconfiguration.html_**

We appreciate your contribution to the program none the less this still violated the rules set by Paytm and the use of Paytm trademarked properties.

This letter serves also as an official notification under Section 512(c) of the Digital Millennium Copyright Act (”DMCA”), and I seek the removal of the aforementioned infringing material from your servers. I request that you immediately notify the infringer of this notice and inform them of their duty to remove the infringing material immediately, and notify them to cease any further posting of infringing material to your server in the future.
 
This is our contact details:
 
Address: Level 30, The Leadenhall Building,
122 Leadenhall Street, EC3V 4AB
City of London, UNITED KINGDOM
Email: izoolabs@izoologic.com
Phone + 44 20 3734 2726
 
I am providing this notice in good faith and with the reasonable belief that rights my company owns are being infringed. 
Should you have any concern please let us know.
 
Thank you.
 
 
Regards, 
Mark Lovinson

**Comment by tutorgeeks** [comment]
Hi team.

The blog article was published long back and I don't remember reading the bug bounty policy of Paytm. Nevertheless, I've removed the blog post.

Thanks.
